name: build

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  macos-run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Install Keystone
        run: |
          brew update
          brew install keystone
  
      - name: Set CGO env
        run: |
          if [ -d "/opt/homebrew/lib" ]; then
            echo "CGO_CFLAGS=-I/opt/homebrew/include" >> $GITHUB_ENV
            echo "CGO_LDFLAGS=-L/opt/homebrew/lib -lkeystone" >> $GITHUB_ENV
          else
            echo "CGO_CFLAGS=-I/usr/local/include" >> $GITHUB_ENV
            echo "CGO_LDFLAGS=-L/usr/local/lib -lkeystone" >> $GITHUB_ENV
          fi
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
  
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
  
      - name: Make Build
        run: make
  
      - name: Test Run
        run: ./build/sgn --version

  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake make gcc g++ python3
  
      - name: Install Keystone
        run: |
          git clone --depth=1 https://github.com/keystone-engine/keystone.git
          cd keystone && mkdir build && cd build
          cmake .. && make -j$(nproc) && sudo make install
  
      - name: Configure library path
        run: |
          echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/keystone.conf
          sudo ldconfig
          echo "CGO_CFLAGS=-I/usr/local/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L/usr/local/lib -lkeystone" >> $GITHUB_ENV
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
  
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
  
      - name: Build
        run: make
  
      - name: Test binary
        run: ./build/sgn --version

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      # 安装 Visual Studio 2022 build tools
      - name: Setup Visual Studio
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 'latest'

      # 安装 CMake
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.26.4'

      # 安装 Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Clone Keystone
      - name: Clone Keystone
        run: |
          git clone --depth 1 https://github.com/keystone-engine/keystone.git
          cd keystone
          mkdir build

      # Build Keystone DLL using official NMake method
      - name: Build Keystone DLL
        shell: cmd
        run: |
          cd keystone\build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON ..
          nmake

      # Build Keystone LIB (optional)
      - name: Build Keystone LIB
        shell: cmd
        run: |
          cd keystone\build
          cmake -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF ..
          nmake

      # Set CGO environment variables for Go
      - name: Set CGO env
        shell: bash
        run: |
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CGO_CFLAGS=-I$GITHUB_WORKSPACE/keystone/include" >> $GITHUB_ENV
          echo "CGO_LDFLAGS=-L$GITHUB_WORKSPACE/keystone/build/llvm/lib -lkeystone" >> $GITHUB_ENV

      # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      # Build sgn
      - name: Build sgn
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          make

      # Test Run
      - name: Test Run
        shell: bash
        run: |
          ./build/sgn.exe --version
